### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by taigacute** [hardcoreplayers/ThinkVim#100]

**Comment by glepnir** [comment]
![1322](https://user-images.githubusercontent.com/41671631/79723871-20723c80-8319-11ea-8cb1-a77917a7ab6d.png)
![git](https://user-images.githubusercontent.com/41671631/79723905-3253df80-8319-11ea-8c7f-d5aeee85b016.gif)
![gruvbox](https://user-images.githubusercontent.com/41671631/79723909-341da300-8319-11ea-9bfb-b4e92a9b06a0.png)
![gruvbox9thinkvim](https://user-images.githubusercontent.com/41671631/79723912-354ed000-8319-11ea-8c92-5572cb1acae9.png)
![kuangdushenyuan](https://user-images.githubusercontent.com/41671631/79723916-367ffd00-8319-11ea-967e-0c56a29da719.png)
![newline](https://user-images.githubusercontent.com/41671631/79723919-37189380-8319-11ea-86d6-5e5c8a7309ec.png)
![statusbar](https://user-images.githubusercontent.com/41671631/79723922-3849c080-8319-11ea-807e-ff349df8c832.png)
![thinkvim-ayu](https://user-images.githubusercontent.com/41671631/79723926-38e25700-8319-11ea-9edb-a5fe41b87deb.png)
![thinkvim](https://user-images.githubusercontent.com/41671631/79723930-3a138400-8319-11ea-857a-c672813df67f.png)
![thinkvim v1](https://user-images.githubusercontent.com/41671631/79723933-3b44b100-8319-11ea-843c-13b7ca1e73b8.png)
![thinkvimline](https://user-images.githubusercontent.com/41671631/79723936-3bdd4780-8319-11ea-922e-0e408b927f6b.png)
![thinkvimnew](https://user-images.githubusercontent.com/41671631/79723940-3c75de00-8319-11ea-9198-1e4d1d9e4912.png)
![vim-space](https://user-images.githubusercontent.com/41671631/79723942-3e3fa180-8319-11ea-855a-dc1193c8fa78.png)

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/79724460-287eac00-831a-11ea-8149-f5a68f19411a.png)

**Comment by glepnir** [comment]
![thinkvim_tmux](https://user-images.githubusercontent.com/41671631/81565109-688df780-93cb-11ea-9d9f-df270a52acdb.png)

**Comment by glepnir** [comment]
![1](https://user-images.githubusercontent.com/41671631/84489554-71c4f980-acd4-11ea-929a-4dfc0f9ea1bf.png)
