### ISSUE TITLE
请问如何自定义插件配置

### ISSUE THREAD

**Issue by yongqi-zhang** [hardcoreplayers/ThinkVim#103]
## What is your expect?
请问是否可以自定义插件配置来覆盖你的配置。比如
call defx#custom#option('_', {
	\ 'show_ignored_files': 1,
  \ })

这里我想在 defx 中显示隐藏文件，但是在 .thinkvim.d/init.vim 中这么写会报错没有此 function。

**Comment by taigacute** [comment]
@yongqi-zhang  按点就显示隐藏文件了。
