### ISSUE TITLE
ThinkVim installation bug.

### ISSUE THREAD

**Issue by ChunjieShan** [hardcoreplayers/ThinkVim#112]
# Problems summary
Hi there!
When I tried to install ThinkVim configuration files, I runned install script, and gave me this message:
![Screenshot from 2020-05-18 16-10-50](https://user-images.githubusercontent.com/49755092/82190477-a6d36b80-9923-11ea-9723-ccb5fb20d284.png)
And when I'm trying open NeoVim, it gave me this message:
![Screenshot from 2020-05-18 16-23-11](https://user-images.githubusercontent.com/49755092/82190646-e8641680-9923-11ea-93f9-84523272ba09.png)
I'll be very glad if you can tell me how to fix it! Thank you very much!

## Environment Information

 * OS: Manjaro
 
 * thinkvim `:echo g:thinkvim_version` output:2.6.1

 * neovim `:version` output:NVIM v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):
![Screenshot from 2020-05-18 16-25-20](https://user-images.githubusercontent.com/49755092/82190838-3842dd80-9924-11ea-97cd-74b5df1abfde.png)

## How to reproduce the problem from neovim startup (Required!)

 1. foo
 2. bar
 3. baz

**Comment by 20jam** [comment]
hmm 🤔. Try renaming/moving .thinkvim.d. Afterwards run make on nvim root dir. 

This issue happens usually when one of the yaml files has syntax errors in them. 

Hope this help you debug and find the root cause.

**Comment by ChunjieShan** [comment]
> hmm . Try renaming/moving .thinkvim.d. Afterwards run make on nvim root dir.
> 
> This issue happens usually when one of the yaml files has syntax errors in them.
> 
> Hope this help you debug and find the root cause.

I've tried to do that but it didn't work. I think system may not read the ~/.config/nvim/core/plugins.yaml correctly, but I've exactly installed pyyaml. Here is the message which dein's log shows:
Target plugins are not found.
You may have used the wrong plugin name, or all of the plugins are already installed.
Runtimepath updated: (2020/05/18 16:45:22)

**Comment by glepnir** [comment]
@ChunjieShan  Please update the pynvim .then remove the .thinvim.d folder and `~/.cache/vim` to reinstall

**Comment by glepnir** [comment]
try this scripts
```console
rm -rf ~/.thinkvim.d
rm -rf ~/.cache/vim
rm -rf ~/.config/nvim
git clone --depth = 1 https://github.com/hardcoreplayers/ThinkVim.git ~/.config/nvim
cd .config/nvim
sh scripts/install.sh
```
note the theme and languages will generate by a excutable file in bin folder.

**Comment by ChunjieShan** [comment]
Oh gosh it finally worked! Thank you for your help!

**Comment by glepnir** [comment]
Thanks for your no love. no thanks for help. 😃
