### ISSUE TITLE
Can't get select default theme selection when execute install.sh

### ISSUE THREAD

**Issue by ShawnRong** [hardcoreplayers/ThinkVim#114]
# Problems summary

Hi, 
  There's error shows every time I opened neovim. Here's the error info:
![image](https://user-images.githubusercontent.com/6622073/83947070-532fb000-a847-11ea-9743-4825b4cafb82.png)
And I checked the code, It looks like all the steps of themes installed by a golang script under 
`cmd/main.go`, And I ran the golang script directly. It shows error:
![image](https://user-images.githubusercontent.com/6622073/83947106-9558f180-a847-11ea-87e2-f420ac7dd494.png)

And I had a temporary solution to fix this, just fixed the options 
```
	colorschemes = []string{ 
		"hardcoreplayers/oceanic-material(support by default)",	
	 }
```
it works.

Any ideas about this issue?

## Environment Information

 * OS: Macos
 
 * thinkvim `:echo g:thinkvim_version` output: 2.6.2

 * neovim `:version` output: v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):

**Comment by glepnir** [comment]
@ShawnRong  Use `Space` to choose colorscheme  then type `Enter` to confirm.

**Comment by ShawnRong** [comment]
Ah, Sorry, I'm not read the command line guide carefully. And thanks for your reply!
