### ISSUE TITLE
What is the `generator` binary you are downloading and executing during install?

### ISSUE THREAD

**Issue by volny** [hardcoreplayers/ThinkVim#122]
Hi, I noticed during install you are downloading a binary from `https://github.com/hardcoreplayers/ThinkVim/releases/download/$version` and executing it. (e.g. https://github.com/hardcoreplayers/ThinkVim/releases/download/v0.1.3/generator-x86_64-linux)

What is this binary and where is the source code for it?

**Comment by glepnir** [comment]
@volny  This binary will write the languages plugin into the `.thinkvim.d/plugins.yaml` according your choice.the binary file is in there https://github.com/hardcoreplayers/ThinkVim/releases
code is https://github.com/hardcoreplayers/ThinkVim/tree/develop/cmd
