### ISSUE TITLE
coc-Rls not found !

### ISSUE THREAD

**Issue by daniel-zou** [hardcoreplayers/ThinkVim#123]
# Problems summary

`.config/nvim/modules/module-lsp.vim`

`coc-Rls` should be `coc-rls` , or there will be "404"

## Environment Information

 * OS: Manjaro Linux
 
 * thinkvim `:echo g:thinkvim_version` output:2.6.5

 * neovim `:version` output:0.4.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)

 1. foo
 2. bar
 3. baz

**Comment by daniel-zou** [comment]
兄弟，没修复啊！我用的npm是腾讯的镜像http://mirrors.cloud.tencent.com/npm/coc-rls，coc-rls可以正常访问、安装，coc-r-lsp，无法访问，tencent应该也是sync的上游，应该也是coc-rls吧。

**Comment by glepnir** [comment]
@daniel-zou  coc-r-lsp 是R语言的, coc-rls是rust 。
https://github.com/neoclide/coc-r-lsp
我不知道你要用什么。 如果写rust thinkvim配置了coc-rust-analyzer

**Comment by daniel-zou** [comment]
是Rust，在安装时，选择哪种语言时，选了Rust。我没选R。启动nvim，在安装coc extension时，安装coc-Rls的时候一直是404，我找到了module.lsp，找到了coc-Rls 改成了coc-rls，安装就顺利完成了。所以，我之前说的就是coc-Rls，改成coc-rls。其他的我都没动呢，还是默认配置。

**Comment by glepnir** [comment]
.thinkvim.d/plugins.yaml 里有R语言么？ rust的lsp已经配置好了。 你打开rust会帮你装server
