### ISSUE TITLE
行59：		if &runtimepath !~# $VIM_PATH

### ISSUE THREAD

**Issue by ongbe** [hardcoreplayers/ThinkVim#124]
什么意思呢？

无效的回引？？？

**Comment by ongbe** [comment]
!~#和!=#一个意思吗

**Comment by glepnir** [comment]
按照格式填写，错误和这行无关

--------------原始邮件--------------
发件人："ongbe "<notifications@github.com&gt;;
发送时间：2020年8月28日(星期五) 上午9:53
收件人："hardcoreplayers/ThinkVim" <ThinkVim@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：Re: [hardcoreplayers/ThinkVim] 行59：  if &amp;runtimepath !~# $VIM_PATH (#124)
-----------------------------------

 

 
!~#和!=#一个意思吗
