### ISSUE TITLE
 coc-marketplace使用后光标消失

### ISSUE THREAD

**Issue by Adnios** [hardcoreplayers/ThinkVim#125]
# Problems summary

:CocList markerplace后，vim光标消失

## Environment Information

 * OS:Ubuntu 18.04
 
 * thinkvim `:echo g:thinkvim_version` output:2.6.5

 * neovim `:version` output:v0.5.0-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'
```

## How to reproduce the problem from neovim startup (Required!)

 1. open vim
 2. :CocList marketplace
 3. the cursor disappear

**Comment by glepnir** [comment]
please update. should be fixed.

**Comment by Adnios** [comment]
大佬，收下我的膝盖
