### ISSUE TITLE
Suggest for good plugins 

### ISSUE THREAD

**Issue by taigacute** [hardcoreplayers/ThinkVim#33]
if you found good plugins , you can subimit it in there. If the plugin is very useful, I will consider adding it。

**Comment by emeentag** [comment]
What do you think `tpope/vim-surround` there might be sth in the package but i could not find it so i decided to use it. I do not know it is good but very common.

**Comment by taigacute** [comment]
i  had add this plugin `rhysd/vim-operator-surround`  instead of `vim-surround`.  `vim-surround` is easy to use . But it is very limited, you can make more functions through textobject
the key map  https://github.com/taigacute/ThinkVim/blob/master/core/plugins/allkey.vim#L258

**Comment by emeentag** [comment]
do you plan to create a gitter channel? For simple q/a

**Comment by taigacute** [comment]
https://gitter.im/thinkvim/Thinkvim

**Comment by baIIoon** [comment]
Have u guys check `vim-sandwich` ? It's like `rhysd/vim-operator-surround`, i just dont know how to use this, so i take `vim-sandwich`

**Comment by taigacute** [comment]
i saw this `vim-sandwich` ,`Surround` plugins are similar to use. It seems to offer a lot of features. A lot of plugins are combined, but for me I don't use too many functions, just add arround, delete or modify. I will take the time to use it to evaluate.

**Comment by baIIoon** [comment]
i have found a way to modify or add `html tag` some kind, just dont know the way to do with `vim-operator-surround`. So `vim-operator-surround`  dont have any to edit `tag` ?

**Comment by taigacute** [comment]
you can custom the  behavior of `vim-opreator-surround`

**Comment by taigacute** [comment]
i  have use `vim-sandwich` instead of `vim-operator-surround`

**Comment by emeentag** [comment]
So are you going to add it to master @taigacute ?

**Comment by taigacute** [comment]
@emeentag  i had add it . lazyload by filetype .  check the usage https://github.com/machakann/vim-sandwich

**Comment by emeentag** [comment]
Can you share the related commit? Thx.

**Comment by taigacute** [comment]
check out [commit](https://github.com/taigacute/ThinkVim/commit/ff59a3d8f5c21a78cd972f85a80643f402830d7d)

**Comment by taigacute** [comment]
@emeentag   i change  the `vim-sandwich` lazyload by `on_map` .

**Comment by baIIoon** [comment]
Do you guys know about `vim-visual-multi`, i just think its so cool

**Comment by sozforex** [comment]
I think https://github.com/wsdjeg/dein-ui.vim can be a good addition.

**Comment by taigacute** [comment]
Is it not necessary? I have provided the denite menu  to manage it. If you like dein-ui you can install it using .thinkvim.d/local_plugins.yaml or local_settings.vim.

**Comment by sozforex** [comment]
It sure is not necessary, just a suggestion =)
