### ISSUE TITLE
默认安装后,按了 <Leader> b, 提示 SPC b is Undefined.

### ISSUE THREAD

**Issue by junmoxiao** [hardcoreplayers/ThinkVim#50]
看了下配置文件,你tutorial写错了
https://github.com/hardcoreplayers/ThinkVim/blob/master/tutorial/tutorial.md
![image](https://user-images.githubusercontent.com/9711902/62339425-8ceca780-b50e-11e9-9d58-c3903176ae2e.png)
```
    <Leader> + b | Normal | fzf find buffer
```
整体来说,真的非常好用,感谢

**Comment by taigacute** [comment]
fixed
