### ISSUE TITLE
有些字体在显示注释时,斜体,会缺失一部分

### ISSUE THREAD

**Issue by junmoxiao** [hardcoreplayers/ThinkVim#51]
![image](https://user-images.githubusercontent.com/9711902/62339927-51eb7380-b510-11e9-8600-c42f3b1457e3.png)

**Comment by taigacute** [comment]
什么终端？是在tmux下？ 字体这个和vim没什么关系，

**Comment by junmoxiao** [comment]
item2,没在tmux下,哪种字体适配好一点?

**Comment by taigacute** [comment]
我用的soucecodepro nerdfont

**Comment by littlepig1337** [comment]
其他字体的话,在iterm2中profile->text中钩上use ligatures就正常显示了
