### ISSUE TITLE
在自定义配置中改了localleader无效

### ISSUE THREAD

**Issue by junmoxiao** [hardcoreplayers/ThinkVim#52]
![image](https://user-images.githubusercontent.com/9711902/62340847-87459080-b513-11e9-8879-c99f35592923.png)

![image](https://user-images.githubusercontent.com/9711902/62340838-7e54bf00-b513-11e9-9bf7-b425ec1ff865.png)

改了之后输入
:echo maplocalleader 
:echo g:maplocalleader
都显示是逗号了
但是按逗号m啥的都没有反应,反而还是按原来的分号m会执行那些功能

**Comment by taigacute** [comment]
这个是这样的 因为localleader在初始化的时候加载 在键位加载之前。用户自定义的是在所有配置之后所以不会生效。
