### ISSUE TITLE
error opening neovim matchit.vim path not found

### ISSUE THREAD

**Issue by smikeblog** [hardcoreplayers/ThinkVim#53]
# Problems summary

on  arch linux error on neovim open  -matchit.vim

## Environment Information

 * OS: linux manjaro

 * neovim `:version` output: neovim 4.0 nightly build

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)
open neovim on linux

 1. foo
 2. bar
 3. baz

## Screenshot (if possible)

NOTE: solution is here:  https://github.com/neovim/neovim/issues/5193
the package path on linux is not /usr/local/share/nvim/... as on OSX is 
but
usr/share/nvim/... 
so add to init.vim
set packpath=/usr/local/share/nvim/runtime
solve the problem.

**Comment by taigacute** [comment]
see here i didnt load it 
https://github.com/hardcoreplayers/ThinkVim/blob/master/core/init.vim#L69

**Comment by smikeblog** [comment]
I deleted all entries and installed Thinkvim as you suggest 
git clone ...
initial nvim install all packages and e-thing is OK!
I close nvim and type 
nvim again Now
This is error when I type nvim at prompt
Error detected while processing /usr/share/nvim/runtime/plugin/matchit.vim:
line    2:
E919: Directory not found in 'packpath': "pack/*/opt/matchit"
Press ENTER or type command to continue
======
After that I add to init.vim file path to matchit.vim path
Now my init.vim is 
 execute 'source' fnamemodify(expand('<sfile>'), ':h').'/core/vimrc'
▎  set packpath=/usr/share/nvim/runtime,~/.local/share/nvim/site
▎ 
and Now error E919 disappear.

P.S. I do not know why only matvhit.vim is looking at /usr/local/share/runtime/...

Thanks for pronpt reply and Good Luck!

**Comment by taigacute** [comment]
hi @smikeblog  can you tell me which neovim version do you used.

**Comment by smikeblog** [comment]
Hi, Of course 
This one 
https://aur.archlinux.org/packages/neovim-nightly

**Comment by taigacute** [comment]
please use the latest nightly neovim version https://github.com/neovim/neovim/releases/  
check vim version by `:version` .

**Comment by smikeblog** [comment]
NVIM v0.4.0-1534-g24fb7eefa
It is compiled today

**Comment by smikeblog** [comment]
it is compile daily from 
source=('https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz')

**Comment by smikeblog** [comment]
Apropos.
The error appeared 2-3 days ago.

**Comment by taigacute** [comment]
then you open nvim . the thinkvim install successful when you see `coc extensions installed` at your nvim cmdline.

**Comment by taigacute** [comment]
ok when i update the latest version , i got your problem.

**Comment by taigacute** [comment]
@smikeblog   i used this version it works well `NVIM v0.4.0-1426-g0e23ee3cc`,maybe its a bug of neovim.

**Comment by smikeblog** [comment]
OK!
If smb has the same problem my solution at the moment is:
mkdir ~/.thinkvim.d
cd ~/.thinkvim.d
touch local_plugins.yaml
echo ' set packpath=/usr/share/nvim/runtime,~/.local/share/nvim/site ' >> local_settings.vim

**Comment by taigacute** [comment]
yes you can add it to .thinkvim.d folder. but i think its a bug of neovim.

**Comment by taigacute** [comment]
@smikeblog   i got the reason of problem .check this neovim commit .https://github.com/neovim/neovim/commit/5342342426777160300a431ef8c9200fb151f793

**Comment by taigacute** [comment]
@smikeblog  fixed.please update.

**Comment by smikeblog** [comment]
OK!
Thanks!
