### ISSUE TITLE
一定长度自动换行有点问题

### ISSUE THREAD

**Issue by littlepig1337** [hardcoreplayers/ThinkVim#54]
![image](https://user-images.githubusercontent.com/53633675/62425764-7e211300-b70f-11e9-9533-d47bf6115d70.png)
比如写这段代码,我再输入个l就变成了
![image](https://user-images.githubusercontent.com/53633675/62425771-8f6a1f80-b70f-11e9-9948-76eca847524b.png)
python这种就语法错误了
![image](https://user-images.githubusercontent.com/53633675/62425797-f38ce380-b70f-11e9-88a9-aea2138f8ff5.png)

默认关闭自动换行?
或者加个80字符的竖线提示一下 set colorcolumn=80
不然用的时候老是怕突然换行

**Comment by taigacute** [comment]
@littlepig1337   嗯 已经加了。
