### ISSUE TITLE
Unable to find a proper YAML parsing utility

### ISSUE THREAD

**Issue by EnziinSystem** [hardcoreplayers/ThinkVim#55]
# Problems summary
[vim-etc] Unable to find a proper YAML parsing utility
[vim-etc] Please upgrade to neovim +v0.1.4 or vim: +v7.4.1304
[vim-etc] 'Vim(return):E474: Unidentified byte: /bin/bash: ruby: command not found^@'
[vim-etc] Error loading /home/kevin/.config/nvim/core/dein/plugins.yaml
[vim-etc] Caught: 'Vim(return):E474: Unidentified byte: /bin/bash: ruby: command not found^@'

Press ENTER or type command to continue

![vim](https://user-images.githubusercontent.com/25495466/62525928-8b85ec80-b838-11e9-92a3-9e6d43e02049.jpg)

## Environment Information

 * OS: Ubuntu 19.04

 * neovim `:version` output: NVIM v0.4.0-1567-gf5d1e0e7b

 * `:checkhealth` or `:CheckHealth` result(neovim only):

**Comment by taigacute** [comment]
@EnziinSystem   hi , please install ruby. because need ruby to parse yaml to vimscript
