### ISSUE TITLE
git clone 之后启动nvim没有自动装插件

### ISSUE THREAD

**Issue by littlepig1337** [hardcoreplayers/ThinkVim#56]
git clone 之后启动nvim没有自动装插件
![image](https://user-images.githubusercontent.com/53633675/62788724-18130200-bafa-11e9-8af5-121aacfabf71.png)

启动之后就一片空白

**Comment by taigacute** [comment]
@littlepig1337  底部没有一直在弹装插件的信息吗

**Comment by littlepig1337** [comment]
没有,我把home目录和.config目录下和vim还有coc相关的目录都删掉,
重新git clone之后,启动nvim,没反应,啥提示也没有

**Comment by taigacute** [comment]
那不应该重新clone之后 会弹出来底部安装dein的提示的，你可以到中文的gitter里说，我可以回复的比较快一点
