### ISSUE TITLE
话说老哥有考虑去掉denite的那些功能吗

### ISSUE THREAD

**Issue by littlepig1337** [hardcoreplayers/ThinkVim#57]
我也看过你b站的视频,像denite那个菜单,你自己也用得不多,我觉得还是尽量保留常用的功能比较好,像这些基本用不到的就不用保留?
还有就是denite的那些功能用着也不方便,输入之后需要回车确认才选择

**Comment by taigacute** [comment]
一直都想去掉，卵用没有，只是没个好的想法。空了我好好研究下
