### ISSUE TITLE
markdown-preview installation error

### ISSUE THREAD

**Issue by Itamiko** [hardcoreplayers/ThinkVim#58]
# Problems summary

Upon first run of this it will error on installing `iamcco/markdown-preview.nvim`
```
[dein] Error installing plugins:
[dein]   markdown-preview.nvim
[dein] Please read the error message log with the :message command.
[dein] Done: (2019/08/10 12:00:57)Press ENTER or type command to continue
```

suspect: 
https://github.com/hardcoreplayers/ThinkVim/blob/c8e48ba0254aae4d223537036a5eca764f726333/core/dein/plugins.yaml#L247

^ might be due to this since I do not have yarn.

## Environment Information

 * OS:
Arch Linux x86_64

 * neovim `:version` output:
```
[tamiko@japan nvim]$ vim -v       
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
    1 health#coc#check
    2 ========================================================================
    3   - OK: Environment check passed
    4   - OK: Javascript bundle found
    5   - OK: Service started
    6 
    7 health#nvim#check
    8 ========================================================================
    9 ## Configuration
   10   - OK: no issues found
   11 
   12 ## Performance
   13   - OK: Build type: Release
   14 
   15 ## Remote Plugins
   16   - OK: Up to date
   17 
   18 ## terminal
   19   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
   20   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   21   - INFO: $VTE_VERSION='5603'
   22   - INFO: $COLORTERM='truecolor'
   23 
   24 health#provider#check
   25 ========================================================================
   26 ## Clipboard (optional)
   27   - OK: Clipboard tool found: xclip
   28 
   29 ## Python 2 provider (optional)
   30   - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
   31   - ERROR: Python provider error:
   32     - ADVICE:
   33       - provider/pythonx: Could not load Python 2:
   34           python2 not found in search path or not executable.
   35           python2.7 not found in search path or not executable.
   36           python2.6 not found in search path or not executable.
   37           /usr/bin/python is Python 3.7 and cannot provide Python 2.
   38   - INFO: Executable: Not found
   39 
   40 ## Python 3 provider (optional)
   41   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
   42   - INFO: Executable: /usr/bin/python3
   43   - INFO: Python version: 3.7.4
   44   - INFO: pynvim version: 0.3.2
   45   - OK: Latest pynvim is installed.
   46 
   47 ## Ruby provider (optional)
   48   - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
   49   - INFO: Host: /home/tamiko/.gem/ruby/2.6.0/bin/neovim-ruby-host
   50   - OK: Latest "neovim" gem is installed: 0.8.1
   51 
   52 ## Node.js provider (optional)
   53   - INFO: Node.js: v11.15.0
   54   - INFO: Neovim node.js host: /home/tamiko/.node_modules/lib/node_modules/neovim/bin/cli.js
   55   - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
   56 

```

## How to reproduce the problem from neovim startup (Required!)

 1. check nvim env
 2. install npm only(*no yarn*)
 3. install ThinkVim `c8e48ba`
 4. open for first run install
5 wait until it's installing markdown-preview
6 error hit

**Comment by taigacute** [comment]
maybe you should install yarn . when you see `--more--` in your command line you should press `enter` to continue

**Comment by taigacute** [comment]
i make a video about install ThinkVim https://www.youtube.com/watch?v=d8MveK-nxkg

**Comment by Itamiko** [comment]
> maybe you should install yarn

Nah I won't be installing yarn, instead, I change `yarn install` to `npm install` which in turn solved my issue.

> when you see --more-- in your command line you should press enter to continue

`[dein] Please read the error message log with the :message command`
this does nothing but say
```
[dein] Error installing plugins:
[dein]   markdown-preview.nvim
```
`[dein] Done: (2019/08/10 12:00:57)Press ENTER or type command to continue`

but it finishes and `ThinkVim` is installed but just without `markdown-preview`

**Comment by taigacute** [comment]
you can use `call dein#update()` to update the plugins if it dosent installed ,it will install . you can also use the command `;+m` then choose dein, and choose update

**Comment by Cyberlane** [comment]
I had this exact problem and the only solution was to install yarn unfortunately. I didn't look into why this one plugin wanted yarn when the rest worked fine with npm.

**Comment by Itamiko** [comment]
Weird for me I just changed yarn part to use npm instead.

**Comment by taigacute** [comment]
@imacco  maybe need the author help. can remove yarn support?

**Comment by iamcco** [comment]
yarn is not required, can use npm instead. It also have a prebuild binary bundle which can run without nodejs. Using `call mkdp#util#install()` function to download prebuild binary bundle, it can be use as hook by plugin manager. `MarkdownPreview` command only available for markdown filetype by default options.

**Comment by taigacute** [comment]
@Itamiko  please `git pull` to update the config , Using the function to install.By the way your neovim version must be 0.4.0 above.
