### ISSUE TITLE
nvim前不要空一列

### ISSUE THREAD

**Issue by IcyHeartBX** [hardcoreplayers/ThinkVim#59]
## nvim前不要空一列
如果想拷贝vim正在编辑的大段文本，我通常的做法是`:set nonu nornu` 然后选择大段文本拷贝，但是`ThinkVim`前面还有一个空列，这样会导致把前面的空列也选中，然后拷贝进去。
请问这个该如何设置呢？

**Comment by taigacute** [comment]
@IcyHeartBX   可以截图看下是哪个空列吗

**Comment by taigacute** [comment]
@IcyHeartBX  我测试了下取消行号和相对行号是没有空列的
![git](https://user-images.githubusercontent.com/41671631/62923730-f8712780-bde0-11e9-8954-cad79af658d8.gif)

**Comment by IcyHeartBX** [comment]
你可能是用V模式没问题，用鼠标拖动选择是有空列的，等我方便时，截个图给你看下

**Comment by IcyHeartBX** [comment]
@taigacute 你可能是用V模式没问题，用鼠标拖动选择是有空列的，等我方便时，截个图给你看下

**Comment by taigacute** [comment]
我不用鼠标。。不怎么了解鼠标下的复制。
