### ISSUE TITLE
Error: Cannot find module 'vscode-languageserver-protoco l' 

### ISSUE THREAD

**Issue by IcyHeartBX** [hardcoreplayers/ThinkVim#62]
# Problems summary
[coc.nvim] Error on load extension coc-post from /home/abc/.config/coc/extensions/
node_modules/coc-post/out/index.js: Error: Cannot find module 'vscode-languageserver-protoco
l' 

## Environment Information

 * OS: Ubuntu 19.04

 * neovim `:version` output:NVIM v0.4.0-1822-ga851090de

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)

 1. `git clone --depth=1 https://github.com/hardcoreplayers/ThinkVim.git ~/.config/nvim`
 2. start nvim
 3.

**Comment by taigacute** [comment]
not thinkvim problem.i have remove the `coc-post` just now.
