### ISSUE TITLE
dein 会自动更新插件吗？

### ISSUE THREAD

**Issue by wuchujiecode** [hardcoreplayers/ThinkVim#63]
## What is your expect?
我发现dein.vim 的文件 好像只有一个检查
```
" Update or install plugins if a change detected
		if dein#check_install()
			if ! has('nvim')
				set nomore
			endif
			call dein#install()
		endif
```
这个函数会自动更新有更新的插件吗

**Comment by taigacute** [comment]
不会,更新都要手动，vim-plug能做到自动更新？

**Comment by wuchujiecode** [comment]
@taigacute vim-plug 也不会自动更新 也需要手动更新但是封装好指令。。这边好像没封装指令。。昨晚研究了一下您的文件。。有一个地方不是很懂是什么作业 能指点一下吗
```
	call etc#util#ensure_directory([
		\   g:etc#cache_path . '/undo',
		\   g:etc#cache_path . '/backup',
		\   g:etc#cache_path . '/session',
		\   g:etc#vim_path . '/spell'
		\ ])
set nospell spellfile=$VIM_PATH/spell/en.utf-8.add
```

**Comment by taigacute** [comment]
dein提供了方法啊 `call dein#update()` 你也可以映射成指令啊。映射成`PlugUpdate` 之类的，我提供了简单的menu方式目前。 `;+m` 选择dein 选择updateplugin就可以了

**Comment by wuchujiecode** [comment]
@taigacute 抱歉  看到了。。因为我一个一个文件单独拆开来看。。插件那个我没有装denite_menu这里。不好意思。。

**Comment by taigacute** [comment]
可以做键位映射 命令映射 这个方法。很简单就实现了类似vim-plug那种
