### ISSUE TITLE
TSX Support

### ISSUE THREAD

**Issue by gfsd3v** [hardcoreplayers/ThinkVim#66]
## What is your expect?

Maybe it would be good to add TSX support out of the box, I not a heavy vim user and I had a little bit of trouble trying to set this up.

**Comment by gfsd3v** [comment]
I get this error while trying to install from the latest commit.

![image](https://user-images.githubusercontent.com/36668882/64869505-e0770880-d617-11e9-8041-b1383c9fff43.png)

**Comment by taigacute** [comment]
Ok, i fixed it. please try agin.

**Comment by gfsd3v** [comment]
Working great, thanks.

**Comment by gfsd3v** [comment]
I saw in the coc-settings that we're using TSLint, it maybe be worth it to think about switching to ESLint sense TSLint is being deprecated, what you guys think ?

**Comment by taigacute** [comment]
Eslint or tslint I think it should be decided by the user, everyone has his own habits, you can make your own custom settings in `.thinkvim.d/local_settings.vim`.

**Comment by gfsd3v** [comment]
Sure, I already change mine, I brought this up only because TSLint is being deprecated, but I guess you will do something about it when it actually is deprecated, thanks for the help and for the awesome repository :)
