### ISSUE TITLE
Probably wrong codepage in spaceline plugin

### ISSUE THREAD

**Issue by argrento** [hardcoreplayers/ThinkVim#81]
# Problems summary
Strange characters in spaceline: some are not shown, some are completely wrong

## Environment Information

 * OS:
Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 * neovim `:version` output:
NVIM v0.5.0-100-g0785f8e8b                                                                                  
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedan
tic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-prot
ector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM
_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/bu
ild/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/n
eovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-620b4ccc-74d6-413b-94e8-8c82101ba196

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#mkdp#check                                                                                                   2 ========================================================================                                            3   - INFO: Platform: linux                                                                                           4   - INFO: Nvim Version: zsh:1: command not found: nvim                                                              5   - INFO: Pre build: /home/user/.cache/vim/dein/repos/github.com/iamcco/markdown-preview.nvim/app/bin/markdown-         preview-linux
    6   - INFO: Pre build version: 0.0.9
    7   - OK: Using pre build
    8 
    9 health#coc#check
   10 ========================================================================
   11   - OK: Environment check passed
   12 
   13   - OK: Javascript bundle found
   14   - OK: Service started
   15 
   16 health#nvim#check
   17 ========================================================================
   18 ## Configuration
   19   - OK: no issues found
   20 
   21 ## Performance
   22   - OK: Build type: RelWithDebInfo
   23                   
   24 ## Remote Plugins 
   25   - OK: Up to date
   26 
   27 ## terminal
   28   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
   29   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   30   - INFO: $VTE_VERSION='5202'   
   31   - INFO: $COLORTERM='truecolor'

## How to reproduce the problem from neovim startup (Required!)

 1. Install neovim
 2. Install ThinkVim
 3. Run neovim

## Screenshot (if possible)
![nvim](https://user-images.githubusercontent.com/4477094/67090131-001ec500-f1b2-11e9-9a52-ffe288bd3113.png)

**Comment by argrento** [comment]
Issue solved after changing font in terminal emulator settings.

**Comment by taigacute** [comment]
@argrento   yes, you need install nerdfont , by the way dont use the neovim appimage. you can download the `nvim-linux64.tar.gz`  from the neovim release then set the bin folder into your env path.
