### ISSUE TITLE
Error executing hook nerdtree

### ISSUE THREAD

**Issue by Cyberlane** [hardcoreplayers/ThinkVim#82]
# Problems summary

When I try to initiate NerdTree with `:NERDTreeeToggle` or `<localleader> + e`, I get the following error

```
[dein] Error occurred while executing hook: nerdtree
[dein] Vim(source):E484: Can't open file /Users/jusnel/.config/nvim/core/plugins/nerdtree.vim
```

The file no longer exists, but it did once... if it has moved, I have no idea where, as i cannot find it when manually searching through the folders?

## Environment Information

 * OS: MacOS 10.14.6

 * neovim `:version` output:

NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5

 * `:checkhealth` or `:CheckHealth` result(neovim only):

Everything is `OK` and green.

## How to reproduce the problem from neovim startup (Required!)

* Open nvim
* Type `:NERDTreeToggle`
* You get the error seen in the screenshot below

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/1614416/67937050-23dc0500-fbcd-11e9-91ab-0835e18250fc.png)

**Comment by taigacute** [comment]
@Cyberlane  Hi  i  had remove nerdtree and add [coc-explorer](https://github.com/weirongxu/coc-explorer)  `leader + j` to toggle coc-explorer

**Comment by Cyberlane** [comment]
Aha, that would explain why I could not find it! :)

I will try out coc-explorer, maybe I can configure it to work the way I like NerdTree to work, thanks!

**Comment by taigacute** [comment]
@Cyberlane  yes coc-explorer is very to use. you can check its keymap by `?` in coc-explorer buffer,then you can config it keymap in coc-settings.json
