### ISSUE TITLE
切换 colortheme & 安装/启动插件

### ISSUE THREAD

**Issue by Azureki** [hardcoreplayers/ThinkVim#84]
很久没更新，最近更新了一次……

# Problems summary
1. 使用 `SPC fc` (`:Colors`) 切换 colorscheme 无效。
错误信息：
> cat '/tmp/nvim0S6237/17'|'/home/user/.cache/vim/dein/repos/github.com/junegunn/fzf/bin/fzf' '--color=bg+:#424450,spinner:#FF79C6,hl:#6272A4,fg:#F8F8F2,header:#6272A4,info:#FF79C6,pointer:#FF79C6,marker:#FF79C6,fg+:#F8F8F2,prompt:#FF79C6,hl+:#FF79C6' +m --prompt="Colors> " --no-height > /tmp/nvim0S6237/16

查看提到的这两个文件，发现 `xxx/17` 里面是 colors-name，`xxx/16`里面为空，这两个文件应该是刚刚执行 `:Colors` 命令时产生的。

## Environment Information

 * OS: linux

 * neovim `:version` output:
v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)

 1. 使用 [readme 中的安装方法](https://github.com/hardcoreplayers/ThinkVim#installation)
 2. make
 3. 打开 neovim，切换 colorscheme

**Comment by Azureki** [comment]
2. 如何不懒加载插件？
在 `~/.thinkvim.d/local_plugins.yaml` 中添加一行 `- repo: psf/black`，然后在 `$VIM_PATH` 下 `make`，提示用 pip 安装 black，成功之后发现确实 black 可以用了。并且在 `~/.cache/vim/dein/repos/github.com/psf/black` 下也确实有 black 这个插件，所以插件应该也安装了。
但是打开neovim， `:Black` 提示找不到命令。我的理解是，不加 `on_map`应该不是懒加载，默认在 neovim 启动时也启动了才对？

**Comment by taigacute** [comment]
make file有点问题,不用make安装 添加好插件直接重启nvim就可以

**Comment by Azureki** [comment]
感谢。不 make，直接打开是可以的，两个问题都解决了。

-----
话说您现在用什么主题？切换到 gruvbox9_hard，发现取消默认透明了。

在 `~/.thinkvim/local_settings.vim` 加上 `let g:gruvbox_transp_bg = 1` 似乎没用，可能是在此之前已经加载了主题。所以只能加在 `VIM_PATH/core/vimrc` 中，但是我觉得还是在local_settings中改更好。

**Comment by taigacute** [comment]
我调整了下theme 初始化函数的位置 放到了 localsetting的后面. gitpull 一下试试

**Comment by Azureki** [comment]
嗯，这下可以了。
