### ISSUE TITLE
setting the cursor width and the color

### ISSUE THREAD

**Issue by gj1118** [hardcoreplayers/ThinkVim#85]
Hi, I am trying to set the cursor width and color. I am using the latest version of Neovim and the latest version of ThinkVim that was released a little time ago. 

![image](https://user-images.githubusercontent.com/473101/70123567-f0175380-1640-11ea-8e5c-a2edff316878.png)

As you can see from the above screenshot , while in Insert mode, the cursor width is really thin and it is not easy to find. 

I do realize that changing the cursor size and position in `iterm` has no effect on the cursor size and color in NeoVim. 

I would like to make it thick and set the color to something bright so that it's easy to find. Can you please let me know what I should be doing to resolve this case ?  

Thanks

**Comment by taigacute** [comment]
This is the performance on my mac. The terminal is iterm2.

![image](https://user-images.githubusercontent.com/41671631/70137014-06b4bd80-16c8-11ea-97df-db297c9d7fe5.png)

**Comment by gj1118** [comment]
Yeah, it seems that your cursor is a bit brighter than mine. That could be because I am overriding some of the colours in my ~/.tmux.config . That said, can you please let me know if there is a way to change the color of the cursor to say $FFC500 (may fav color) and increase the thickness of the cursor (because even in your screenshot its a bit thin) . 

thanks

**Comment by taigacute** [comment]
I have tried to set it on terminal ,but failed. this [article](https://vim.fandom.com/wiki/Configuring_the_cursor) is change cursor on gvim
