### ISSUE TITLE
Auto lint on save happens after saving

### ISSUE THREAD

**Issue by 191205** [hardcoreplayers/ThinkVim#88]
First of all Great Product, you did a great job. ThinkVim is the best out there
# Problems summary

When I save my edits of js and vue files, it saves first then fix.

## Environment Information

 * OS: Arch

 * neovim `:version` output: Latest

 * `:checkhealth` or `:CheckHealth` result(neovim only): No Errors

## How to reproduce the problem from neovim startup (Required!)

 1. edit
 2. :w

**Comment by taigacute** [comment]
thanks for your love, can you show me with a gif or video? i had add `coc-vetur ` on thinkvim please try it

**Comment by 191205** [comment]
Hay, Thank you so much for your quick replay, 

So I've found out that the issue was with the following lines I added to filetype.vim:
```
" autocmd WinEnter,InsertLeave * set cursorline
" autocmd WinLeave,InsertEnter * set nocursorline
```

After taking it out it, the issue has been resolved.

Is there a way to have cursor highlight without those autocmd?

Another Errors I've been having, even with fresh clone with the repo is:
```
[coc.nvim] languageserver will save operation after 0.5s
[coc.nvim] error: Uncaught exception: Error: spawn /home/a/.config/coc/extentions/coc-tabnine-data/binaries/2.1.22/x86_64-unknown-linux-musl/TabNine EACCES 
     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
     at onErrorNT (internal/child_process.js:468:16)
     at processTickAndRejections (internal/process/task_queues.js:84:21)
```

as well as : TabNine timeout errors

**Comment by taigacute** [comment]
you can `set cursorcolumn set cursorline` to highlight col and row.    its a problem of coc-tabnine not thinkvim
