### ISSUE TITLE
Change gopath and goroot

### ISSUE THREAD

**Issue by SlippyJimmy** [hardcoreplayers/ThinkVim#89]
`Error: Command failed: env GOBIN=/Users/vimer/.config/coc/extensions/coc-go-data
/bin GOPATH=/Users/vimer/.config/coc/extensions/coc-go-data/tools go get -u gola
ng.org/x/tools/cmd/gopls`
I want to change the GoPath and GoRoot, Where to edit it?

**Comment by taigacute** [comment]
the gopath is setting on your path file like zshrc or bashrc
