### ISSUE TITLE
global variable `markdown_fenced_languages` can not be modified

### ISSUE THREAD

**Issue by yech1990** [hardcoreplayers/ThinkVim#91]
When opening a markdown file with thinkvim config, `:echo g:markdown_fenced_languages` command always return `['html', 'python', 'bash=sh']`. And languages except python and html are not rendered correctly.

![image](https://user-images.githubusercontent.com/5415510/73329986-65e31880-429a-11ea-849a-37fc168561d8.png)

---

more info:

1. This variable has be redefined in `~/.config/nvim/core/dein/plugins.yaml`, but it seems to be not work.
2. This variable is not defined in other config files within &rtp.

**Comment by taigacute** [comment]
i got this `['html', 'bash=sh', 'css', 'javascript', 'jsx=javascriptreact', 'tsx=typescriptreact', 'go']
`

**Comment by yech1990** [comment]
Hi @taigacute, the latest commit still can not fix the issue.

```vim
:echo g:markdown_fenced_languages
```

**Comment by taigacute** [comment]
use this 
```viml
:echo g:vim_markdown_fenced_languages
```
