### ISSUE TITLE
额。coc-tabnine貌似不支持手机

### ISSUE THREAD

**Issue by htname** [hardcoreplayers/ThinkVim#92]
![Screenshot_20200130_162439](https://user-images.githubusercontent.com/59814884/73432251-ec820f00-4307-11ea-8396-5b2d906f11fc.jpg)
![Screenshot_2020_0130_162750](https://user-images.githubusercontent.com/59814884/73432335-22bf8e80-4308-11ea-9fd8-76d6f60b33df.jpg)
手机架构问题？
手机体验不错，就是这个插件报错

**Comment by taigacute** [comment]
嗯 tabnine 是个rust打包的程序。手机上不支持的。可以加个判断？不知道能不能判断是不是手机vim？

**Comment by htname** [comment]
用uname好像可以判断。。。

**Comment by taigacute** [comment]
那可以简单的加个判断。就好了。
