### ISSUE TITLE
Poor find file performance with icons

### ISSUE THREAD

**Issue by ubmarco** [hardcoreplayers/ThinkVim#93]
# Problems summary

When running `<leader>+f+f` (find file) on a folder with a fair amount of files (in my case 38.000) I experience a big delay (9s) until the floating window appears. Problem is that dev icons are collected upfront for all files. The delay is also several seconds on less files - e.g. 9.000 which I often have in the environment I work.

These are the first items of the neovim profiling output:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   9.530465   0.004144  Fzf_dev()
    1   9.193987   0.010084  <SNR>87_files()
    1   8.990296   1.613361  <SNR>87_prepend_icon()
38440   7.376935   7.018629  WebDevIconsGetFileTypeSymbol()
38460   0.358549             <SNR>48_DevIconsGetArtifactFix()
    1   0.331276   0.226557  fzf#run()
    1   0.097137   0.000507  which_key#start()
    2   0.080172   0.000066  which_key#window#show()
38440   0.079961             <SNR>38_enc_to_cp()
    2   0.063552   0.001302  which_key#wait_for_input()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
38440   7.376935   7.018629  WebDevIconsGetFileTypeSymbol()
    1   8.990296   1.613361  <SNR>87_prepend_icon()
38460              0.358549  <SNR>48_DevIconsGetArtifactFix()
    1   0.331276   0.226557  fzf#run()
38440              0.079961  <SNR>38_enc_to_cp()
    2   0.023327   0.023313  <SNR>44_request()
    2   0.013351   0.013009  <SNR>78_getchar()
    1   0.035184   0.012326  which_key#map#parse()
```
So this takes more than 9 seconds for me while running `rg --files` on the xfce4-terminal takes just 0.5s (or `fzf`, it's equally fast).

## Environment Information

 * OS: Manjaro

 * neovim `:version` output:
```
NVIM v0.4.3                                                                                                                                                      
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototyp
es -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATI
ONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/ne
ovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5803'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/sbin/python2
  - INFO: Other python executable: /usr/bin/python2
  - INFO: Other python executable: /sbin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.4.0 (outdated; from /usr/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/sbin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.1
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v13.7.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.5.0, latest: 4.8.0
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## How to reproduce the problem from neovim startup (Required!)

 1. cd into a directory with a lot files
 2. type `<leader>+f+f` (`space+f+f`)
 3. observe the delay until the floating window appears

## Screenshot (if possible)
![Peek 2020-02-25 20-26](https://user-images.githubusercontent.com/839934/75280583-00893580-580e-11ea-9ed9-d9b609d745f4.gif)
[profile.log](https://github.com/hardcoreplayers/ThinkVim/files/4251792/profile.log)

**Comment by taigacute** [comment]
Please install `bat`

**Comment by ubmarco** [comment]
The message tells `[bat error]: './Riot/SingletonLock: No` and on the left side I see 'No such file or directory', so it looks like this is a condition in which fzf finds the file but it gets deleted in the time span of the command run.
If `bat` wouldn't be installed, I'd get `zsh:1: command not found: bat`.
I think you don't see the issue because you're running the command on 441 files which is much less. Just did a couple of sketchy tests on my current machine:

| file count | delay |
| --- | --- |
| 400 | instant |
| 2600 | 1s |
| 10800 | 2s |
| 31000 | 5s |
| 44000 | 7s |
| 75000 | 13s |

So it comes down to the project size. When I run the following on a command line
```
marco@tux01 $ time rg --files | wc
  43142   45758 5760746
rg --files  0.62s user 0.43s system 492% cpu 0.213 total
wc  0.08s user 0.00s system 40% cpu 0.213 total
```
it shows that searching for 43000 files takes just 0.2 seconds.

**Comment by taigacute** [comment]
Did you set rg ignore file?

**Comment by taigacute** [comment]
closed.

**Comment by ubmarco** [comment]
Here is a patch that comments out the icon fetching code. 
```
diff --git layers/+completion/fzf/config.vim layers/+completion/fzf/config.vim
index 304df5d..6f9b7cb 100644
--- layers/+completion/fzf/config.vim
+++ layers/+completion/fzf/config.vim
@@ -74,8 +74,8 @@ let l:fzf_files_options = ' -m --bind ctrl-d:preview-page-down,ctrl-u:preview-pa
     let result = []
     for candidate in a:candidates
       let filename = fnamemodify(candidate, ':p:t')
-      let icon = WebDevIconsGetFileTypeSymbol(filename, isdirectory(filename))
-      call add(result, printf("%s %s", icon, candidate))
+      " let icon = WebDevIconsGetFileTypeSymbol(filename, isdirectory(filename))
+      call add(result, printf("%s", candidate))
     endfor
 
     return result
```
This reduces the `<leader>+f+f` load time of 42k files by a factor of 10 which is completely acceptable for me.
I totally see that this issue might only affect big projects. I see the following solutions:
- introduce a configuration parameter to deactivate the icon loading for the screen
- adapt the implementation to stop loading icons if the list of files is bigger than x elements (maybe also configurable because it depends on the machine performance)

I'd appreciate the second solution. If I run `<leader>+f+f` on my home directory (400k files) accidentally I commonly have to hard kill the nvim process because I can't wait for minutes.

Do you see room for improvement?

**Comment by taigacute** [comment]
the latest version of thinkvim , used the `fzf-preview.vim` instead of my hack function.  this setting of `fzf-preview.vim` is disabled on thinkvim
```viml
 Use vim-devicons
let g:fzf_preview_use_dev_icons = 0
```

Regarding judging the number of files by opening the icon and getting the returned number of rg can do this, I will study if there is time to implement it.

**Comment by taigacute** [comment]
@ubmarco This is a comparison of speed, fzf and coclist files, you can see that coclist is faster. But the display effect is not as comfortable as fzf.
![test](https://user-images.githubusercontent.com/41671631/75540588-46850a00-5a57-11ea-9930-48e8722d8e42.gif)

**Comment by ubmarco** [comment]
Thanks for that feedback. The new `fzf-preview.vim` solution has a great performance. Also activating the dev icons works (if needed on project basis). However I get an error on every interaction (ESC / select) with the preview window.:
```
-- TERMINAL --
Close "term://.//7785:cat '/tmp/nvim0PUsUl/3'|'/home/marco/.cache/vim/dein/repos/github.com/junegunn/fzf/bin/fzf' --multi --reverse --ansi 
--bind=ctrl-d:preview-page-down,ctrl-u:preview-page-up,?:toggle-preview   --expect=ctrl-v,ctrl-x,ctrl-q,ctrl-t --prompt="DirectoryFiles> " 
--preview='[[ "$(file --mime {})" =~ binary ]] && echo "{} is a binary file" || head -100 {-1}'  --no-height > /tmp/nvim0PUsUl/2;#FZF"?    
[Y]es, (N)o, (C)ancel:
```
![Peek 2020-03-02 10-39](https://user-images.githubusercontent.com/839934/75664198-5cbae200-5c72-11ea-891e-4c5471d15472.gif)

**Comment by taigacute** [comment]
@ubmarco  maybe some error on fzf. i am not fzf pro.please ask this question on fzf. because i cant reproduce it .works fine for me.
