### ISSUE TITLE
Ubuntu18.04安装失败

### ISSUE THREAD

**Issue by liguangcai** [hardcoreplayers/ThinkVim#96]
工具准备就绪后输入nvim出现错误：
Error detected while processing CursorHold Autocommands for "*":
E117: Unknown function: CocActionAsync

**Comment by taigacute** [comment]
@liguangcai  coc没装上。挂个代理之类的。可能你git npm网络不稳定。

**Comment by liguangcai** [comment]
应该不是，用vim可以安装coc，不知道你这个环境怎么单独安装coc？

**Comment by taigacute** [comment]
网络环境问题 npm用淘宝镜像.
``viml
:call dein#install('coc.nvim')
```

**Comment by taigacute** [comment]
没有反馈，关闭此issue。
