### ISSUE TITLE
Question: How to append to vim-which-key dictionary from local_settings.vim?

### ISSUE THREAD

**Issue by quisenbeje** [hardcoreplayers/ThinkVim#97]
# Problems summary
I am setting up my local keymaps (in ~/.thinkvim.d/local_settings.vim). I'd really like to be able to register them with vim-which-key, but I can't work out how to do that from local_settings.vim. Is this possible?

![scrn-2020-03-03-10-31-58](https://user-images.githubusercontent.com/1675985/75797345-a7a02c80-5d3a-11ea-842c-8e2ce6bd0124.png)

I've made several attempts with no luck. When attempted with the file shown above, I get the following error message from nvim.

```
Error detected while processing /home/quisenbeje/.thinkvim.d/local_settings.vim:
line   29:
E121: Undefined variable: g:which_key_map
line   31:
E121: Undefined variable: g:which_key_map
line   33:
E121: Undefined variable: g:which_key_map
Press ENTER or type command to continue
```

**Comment by taigacute** [comment]
please update . had fixed.
