### ISSUE TITLE
切换到 fzf-preview 后会有 Close term 提示

### ISSUE THREAD

**Issue by tinytub** [hardcoreplayers/ThinkVim#98]
请问您切换到 fzf-preview 后会有 close term 的提示吗?
参考了一下 https://github.com/yuki-ycino/fzf-preview.vim/issues/86 也没有太好的解决方案
想问一下,您这边是怎么处理的?

**Comment by taigacute** [comment]
我工作很正常，没遇到这个提示

**Comment by tinytub** [comment]
set confirm 能行,不过我手潮,可能会导致忘记存文件直接就退出了.我也关注一下 fzf-preview 那边有没有其他进展.

**Comment by taigacute** [comment]
是那边的问题，因为之前是正常的，更新了之后就有了。可以用coclist files 搜索，也很快。等fzf解决了在使用fzf也可以。

**Comment by taigacute** [comment]
@tinytub  那边解决了更新就可以了。

**Comment by tinytub** [comment]
好的，感谢
