### ISSUE TITLE
脚本安装coc失败

### ISSUE THREAD

**Issue by SlippyJimmy** [hardcoreplayers/ThinkVim#99]
# Problems summary

[action]:
 ⇒ Install coc extensions...
 ⇒  Create extensions dir:
bin/install.sh: line 56: syntax error near unexpected token `fi'
bin/install.sh: line 56: `fi'
## Environment Information

 * OS:Mac 10.15.1
 
 * thinkvim `:echo g:thinkvim_version` output:

 * neovim `:version` output:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem from neovim startup (Required!)

 1. foo
 2. bar
 3. baz

**Comment by taigacute** [comment]
@SlippyJimmy  我刚更新了。试一下，你是linux吗？报错呢？

**Comment by SlippyJimmy** [comment]
又出现了其他问题
[action]:
 ⇒ Install coc extensions...
 ⇒  Create extensions dir:
[error] package.json duplicate.

**Comment by taigacute** [comment]
@SlippyJimmy  因为你第一次构建的时候生成了这个文件，所以重复了。我判断下删除吧.更新就可以了；

**Comment by liguangcai** [comment]
刚刚pull的，我的用脚本是这样，但是好像make就可以，在xshell运行，颜色有点奇怪，是不是开了真彩什么的了？    
~/.config/nvim   master  sh bin/install.sh
bin/install.sh: 3: bin/install.sh: source: not found
bin/install.sh: 4: bin/install.sh: source: not found
bin/install.sh: 8: bin/install.sh: action: not found
bin/install.sh: 10: bin/install.sh: Syntax error: "(" unexpected  
![image](https://user-images.githubusercontent.com/48577411/78862355-c98f7c00-7a69-11ea-9894-51917ebd0c07.png)
![image](https://user-images.githubusercontent.com/48577411/78862375-d90ec500-7a69-11ea-88ca-2edf072079d7.png)

**Comment by taigacute** [comment]
开了truecolor。你这个看着好奇怪，为什么脚本挂了。

**Comment by HandsomeMan2** [comment]
环境是Ubuntu18.04  
还有另一个问题：  
命令行执行： ctags --version | grep Exuberant
输出：Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert     
打开一个文件：底下有错误，gutentags: ctags job failed, returned:1

**Comment by taigacute** [comment]
@HandsomeMan2 能试下ubuntu默认的是terminal吗。ctags这个是有问题的但是我不知道在linux的正确安装姿势。我查查。

**Comment by HandsomeMan2** [comment]
我看你的脚本是这样  #!/usr/bin/env bash  
然后我执行 bash bin/install.sh可以

**Comment by taigacute** [comment]
这个是会查找你系统的bash来调用。为什么你那里要指定调用。。这里是ctags的问题
https://github.com/ludovicchabant/vim-gutentags/issues/169，mac下很好解决，linux我在看看

**Comment by HandsomeMan2** [comment]
@taigacute 好的谢谢，我自己也研究一下，这个脚本每次运行都会全部重装，比make的时候久很多

**Comment by taigacute** [comment]
@HandsomeMan2  脚本会安装所有依赖这样用户就不用自己一个个去装，时间可能是node安装coc的extensions导致的，node使用淘宝镜像会快很多。

**Comment by taigacute** [comment]
@SlippyJimmy  Closed

**Comment by SlippyJimmy** [comment]
已经解决了，多谢作者指点，另外我用的goproxy把gopls安装上了，但是还是报错，错误代码如下：
[coc.nvim] Server languageserver.golang failed to start: Command "gopls" of languageserver.golang is not executable: Error: not found: gopls
System macOS 10.15.4
go version 14.1

**Comment by taigacute** [comment]
@SlippyJimmy  提示没有找到gopls, `gopls -v` 输出
